// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warning04436bc67b2249d0571baa0b11af9901fa0b7a793420ad0d03485b6d394459c2() {}
